version: '3.4'

services:

  db:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=${DATABASE_USERNAME}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
    volumes:
      - appdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always
    networks:
      - db-network
  redis:
    image: redis:latest
    volumes:
      - appcache:/data
    networks:
      - redis-network
    restart: always
    ports:
      - 6379:6379

volumes:
  appdata: null
  appcache: null
  esdata: null

networks:
  db-network:
    driver: bridge
  redis-network:
    driver: bridge
  es-network:
    driver: bridge
