name: 📀

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  base:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        name: Checkout lastest code
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get release version
        run: echo "RELEASE_VERSION=1.0.0" >> $GITHUB_ENV
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          target: base
          tag: 'base'
          push: false
          outputs: type=docker,dest=/tmp/base.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'base'
          path: /tmp/base.tar
  gateway:
    name: Build gateway image
    needs: base
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: 'base'
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
